version: '3'
services:
  db:
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/webdata
    ports:
      - 5433:5433
    environment:
      POSTGRES_DB: testservicedb
      POSTGRES_USER: testserviceuser@test-payment-dev
      POSTGRES_PASSWORD: Testtest!1
    command: -p 5433
volumes:
  db-data: